### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by HeyZoos**
Just found a few typos while I was reading through the docs

### CODE REVIEW

**Comment by JosePedroDiasSky** [comment]
awesome thanks

**Comment by JosePedroDiasSky** [comment]
archive I'm not part of sapo anymore so I'm unable to merge

**Comment by JosePedroDiasSky** [comment]
you can contribute to my original branch though, here:
https://github.com/josepedrodias/inkdoc

**Comment by pedrocorreia** [comment]
Hi @HeyZoos, sorry for the ridiculous response time and thanks for your contribution.

**Pull request merged**
